baseURL = 'https://nerdhirn.tech/'
locale = 'en-US'
title = 'nerdhirn'
theme = ["github.com/dzello/reveal-hugo"]
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true
relativeURLs = true
uglyURLs = false

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "nerdhirn helps small teams make IT easier with automation, friendly technical support, efficient computing environments, and scalable problem solving."
  author = "Brandon B"
  businessName = "nerdhirn"
  businessLegalName = "nerdhirn.tech"
  tagline = "Managed IT automation and friendly technical support"
  contactUrl = "https://cal.com/brandonb.tech"
  keywords = [
    "managed IT support",
    "IT automation",
    "technical support",
    "computing environments",
    "small business IT",
    "end-user support"
  ]

[params.reveal_hugo]
  custom_theme = "stylesheets/nimbi.css"
  #enableSourceMap = true
  #custom_theme_compile = true

#[reveal_hugo.custom_theme_options]
  #targetPath = "stylesheets/nimbi.css"
  #enableSourceMap = true

[outputFormats.Reveal]
  baseName = "index"
  mediaType = "text/html"
  isHTML = true

[services]
  [services.googleAnalytics]
    id = 'G-BZGNL371G8'
